name: avigna
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.29.3"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  cupertino_icons: ^1.0.2
#  google_fonts: ^3.0.1
#  new packages
  google_fonts: ^4.0.0
#  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #  new packages
  file: ^7.0.0
  path_provider: ^2.1.0
  win32: ^5.12.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


